# Generated by Django 4.2.7 on 2025-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal/Headmaster'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='TEACHER', max_length=20),
        ),
    ]
