# Generated by Django 4.2.7 on 2026-01-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_dailyattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviour',
            name='remarks',
        ),
        migrations.AddField(
            model_name='behaviour',
            name='class_teacher_remarks',
            field=models.TextField(blank=True, help_text="Class teacher's remarks about the student"),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='interest',
            field=models.CharField(choices=[('READING_WRITING', 'Reading, Writing'), ('MATHEMATICS_SCIENCE', 'Mathematics, Science'), ('SPORTS_GAMES', 'Sports, Games'), ('ARTS_CRAFTS', 'Arts, Crafts'), ('MUSIC_DANCING', 'Music, Dancing'), ('TECHNOLOGY_COMPUTERS', 'Technology, Computers'), ('SOCIAL_ACTIVITIES', 'Social Activities'), ('LEADERSHIP_ACTIVITIES', 'Leadership Activities'), ('VARIED_INTERESTS', 'Varied Interests')], default='VARIED_INTERESTS', max_length=30),
        ),
    ]
