# Generated by Django 4.2.7 on 2026-01-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_behaviour_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviour',
            name='promoted_to',
            field=models.CharField(blank=True, help_text='Next class/level student is promoted to', max_length=100),
        ),
    ]
