# Generated by Django 4.2.7 on 2026-01-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_behaviour_promoted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviour',
            name='interest',
            field=models.CharField(blank=True, help_text="Student's interests and hobbies", max_length=100),
        ),
    ]
