# Generated by Django 4.2.7 on 2026-03-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_behaviour_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Student absence/late reason sent to teacher'),
        ),
    ]
