# Generated by Django 4.2.7 on 2026-01-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assignment_id',
            field=models.IntegerField(blank=True, help_text='Related assignment ID', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='class_id',
            field=models.IntegerField(blank=True, help_text='Related class ID', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('assignment', 'Assignment')], default='info', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['assignment_id'], name='notificatio_assignm_d24b83_idx'),
        ),
    ]
