# Generated by Django 4.2.7 on 2026-02-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_assignment_id_notification_class_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_05b4bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_assignm_d24b83_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='class_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
    ]
