# Generated by Django 4.2.7 on 2026-02-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_notificatio_user_id_05b4bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='assignment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('assignment', 'Assignment'), ('fee', 'Fee'), ('general', 'General'), ('warning', 'Warning'), ('success', 'Success')], default='general', max_length=20),
        ),
    ]
