#!/usr/bin/env python3
"""
Professional wkhtmltopdf Installation Script for Windows
Ensures PDF generation works identically to HTML preview
"""

import os
import sys
import subprocess
import urllib.request
import tempfile
import shutil
from pathlib import Path

def check_admin_rights():
    """Check if script is running with administrator privileges"""
    try:
        import ctypes
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        return False

def download_wkhtmltopdf():
    """Download wkhtmltopdf installer for Windows"""
    print("📥 Downloading wkhtmltopdf installer...")
    
    # wkhtmltopdf download URL for Windows 64-bit
    url = "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.msvc2015-win64.exe"
    
    # Create temp directory
    temp_dir = tempfile.mkdtemp()
    installer_path = os.path.join(temp_dir, "wkhtmltopdf_installer.exe")
    
    try:
        urllib.request.urlretrieve(url, installer_path)
        print(f"✅ Downloaded installer to: {installer_path}")
        return installer_path
    except Exception as e:
        print(f"❌ Failed to download wkhtmltopdf: {e}")
        return None

def install_wkhtmltopdf(installer_path):
    """Install wkhtmltopdf silently"""
    print("🔧 Installing wkhtmltopdf...")
    
    try:
        # Run installer silently
        result = subprocess.run([
            installer_path, 
            "/S",  # Silent install
            "/D=C:\\Program Files\\wkhtmltopdf"  # Install directory
        ], capture_output=True, text=True, timeout=300)
        
        if result.returncode == 0:
            print("✅ wkhtmltopdf installed successfully!")
            return True
        else:
            print(f"❌ Installation failed: {result.stderr}")
            return False
            
    except subprocess.TimeoutExpired:
        print("❌ Installation timed out")
        return False
    except Exception as e:
        print(f"❌ Installation error: {e}")
        return False

def verify_installation():
    """Verify wkhtmltopdf is properly installed"""
    print("🔍 Verifying installation...")
    
    wkhtmltopdf_path = r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
    
    if not os.path.exists(wkhtmltopdf_path):
        print(f"❌ wkhtmltopdf not found at: {wkhtmltopdf_path}")
        return False
    
    try:
        # Test wkhtmltopdf version
        result = subprocess.run([wkhtmltopdf_path, "--version"], 
                              capture_output=True, text=True, timeout=10)
        
        if result.returncode == 0:
            print(f"✅ wkhtmltopdf is working: {result.stdout.strip()}")
            return True
        else:
            print(f"❌ wkhtmltopdf test failed: {result.stderr}")
            return False
            
    except Exception as e:
        print(f"❌ Verification error: {e}")
        return False

def test_pdf_generation():
    """Test PDF generation with sample HTML"""
    print("🧪 Testing PDF generation...")
    
    wkhtmltopdf_path = r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
    
    # Create sample HTML
    sample_html = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Test Report</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { background: #000; color: white; padding: 10px; text-align: center; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th, td { border: 1px solid #000; padding: 8px; text-align: center; }
            th { background: #f0f0f0; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>SCHOOL REPORT TEST</h1>
        </div>
        <h2>Student: John Doe</h2>
        <table>
            <tr><th>Subject</th><th>Score</th><th>Grade</th></tr>
            <tr><td>Mathematics</td><td>85</td><td>A</td></tr>
            <tr><td>English</td><td>78</td><td>B</td></tr>
        </table>
        <p>This is a test PDF generated by wkhtmltopdf.</p>
    </body>
    </html>
    """
    
    try:
        # Create temp files
        with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8') as temp_html:
            temp_html.write(sample_html)
            temp_html_path = temp_html.name
        
        temp_pdf_path = temp_html_path.replace('.html', '.pdf')
        
        # Generate PDF
        cmd = [
            wkhtmltopdf_path,
            '--page-size', 'A4',
            '--margin-top', '10mm',
            '--margin-right', '10mm',
            '--margin-bottom', '10mm',
            '--margin-left', '10mm',
            '--print-media-type',
            '--encoding', 'UTF-8',
            temp_html_path,
            temp_pdf_path
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        
        if result.returncode == 0 and os.path.exists(temp_pdf_path):
            file_size = os.path.getsize(temp_pdf_path)
            print(f"✅ PDF generation successful! Generated {file_size} bytes")
            
            # Cleanup
            os.unlink(temp_html_path)
            os.unlink(temp_pdf_path)
            return True
        else:
            print(f"❌ PDF generation failed: {result.stderr}")
            return False
            
    except Exception as e:
        print(f"❌ PDF test error: {e}")
        return False

def update_django_settings():
    """Update Django settings with correct wkhtmltopdf path"""
    print("⚙️ Updating Django settings...")
    
    settings_path = Path(__file__).parent / "school_report_saas" / "settings.py"
    
    if not settings_path.exists():
        print(f"❌ Django settings not found at: {settings_path}")
        return False
    
    try:
        # Read current settings
        with open(settings_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if wkhtmltopdf config exists
        if 'WKHTMLTOPDF_CMD' in content:
            print("✅ wkhtmltopdf configuration already exists in settings.py")
        else:
            # Add wkhtmltopdf configuration
            wkhtmltopdf_config = '''
# wkhtmltopdf configuration for PDF generation
if os.name == 'nt':  # Windows
    WKHTMLTOPDF_CMD = r"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"
else:  # Linux/Unix
    WKHTMLTOPDF_CMD = '/usr/local/bin/wkhtmltopdf'
'''
            
            # Add before the last line
            content = content.rstrip() + wkhtmltopdf_config + '\n'
            
            with open(settings_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print("✅ Added wkhtmltopdf configuration to settings.py")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to update settings: {e}")
        return False

def main():
    """Main installation process"""
    print("🚀 Professional wkhtmltopdf Installation for School Report System")
    print("=" * 60)
    
    # Check if already installed
    if os.path.exists(r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"):
        print("✅ wkhtmltopdf is already installed!")
        if verify_installation() and test_pdf_generation():
            print("\n🎉 wkhtmltopdf is working perfectly!")
            update_django_settings()
            return True
    
    # Check admin rights
    if not check_admin_rights():
        print("❌ This script requires administrator privileges.")
        print("   Please run as administrator (Right-click -> Run as administrator)")
        return False
    
    # Download installer
    installer_path = download_wkhtmltopdf()
    if not installer_path:
        return False
    
    try:
        # Install wkhtmltopdf
        if not install_wkhtmltopdf(installer_path):
            return False
        
        # Verify installation
        if not verify_installation():
            return False
        
        # Test PDF generation
        if not test_pdf_generation():
            return False
        
        # Update Django settings
        update_django_settings()
        
        print("\n🎉 SUCCESS! wkhtmltopdf is now ready for PDF generation!")
        print("\nNext steps:")
        print("1. Restart your Django development server")
        print("2. Test PDF generation in your application")
        print("3. PDFs will now render identically to HTML previews")
        
        return True
        
    finally:
        # Cleanup installer
        try:
            if installer_path and os.path.exists(installer_path):
                os.unlink(installer_path)
                shutil.rmtree(os.path.dirname(installer_path))
        except:
            pass

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)