#!/usr/bin/env python
"""
ReportLab Installation and Setup Script
Ensures ReportLab is properly installed for Windows PDF generation
"""

import sys
import subprocess
import os

def check_reportlab():
    """Check if ReportLab is installed and working"""
    try:
        import reportlab
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib import colors
        from reportlab.lib.units import inch, mm
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
        
        print("✅ ReportLab is installed and all required modules are available")
        print(f"   Version: {reportlab.Version}")
        return True
    except ImportError as e:
        print(f"❌ ReportLab is not properly installed: {e}")
        return False

def install_reportlab():
    """Install ReportLab using pip"""
    print("Installing ReportLab...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "reportlab"])
        print("✅ ReportLab installed successfully")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to install ReportLab: {e}")
        return False

def test_basic_pdf():
    """Test basic PDF creation"""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
        from io import BytesIO
        
        # Create a simple PDF in memory
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        styles = getSampleStyleSheet()
        
        story = [
            Paragraph("ReportLab Test PDF", styles['Title']),
            Spacer(1, 12),
            Paragraph("This is a test PDF generated by ReportLab.", styles['Normal']),
            Spacer(1, 12),
            Paragraph("If you can see this, ReportLab is working correctly!", styles['Normal'])
        ]
        
        doc.build(story)
        pdf_content = buffer.getvalue()
        buffer.close()
        
        # Save test PDF
        test_file = os.path.join(os.path.dirname(__file__), 'reportlab_test.pdf')
        with open(test_file, 'wb') as f:
            f.write(pdf_content)
        
        print(f"✅ Basic PDF test successful - saved to {test_file}")
        print(f"   PDF size: {len(pdf_content)} bytes")
        return True
        
    except Exception as e:
        print(f"❌ Basic PDF test failed: {e}")
        return False

def update_requirements():
    """Update requirements.txt to include ReportLab"""
    requirements_file = os.path.join(os.path.dirname(__file__), 'requirements.txt')
    
    if not os.path.exists(requirements_file):
        print("⚠️  requirements.txt not found")
        return
    
    # Read current requirements
    with open(requirements_file, 'r') as f:
        requirements = f.read()
    
    # Check if reportlab is already in requirements
    if 'reportlab' in requirements.lower():
        print("✅ ReportLab is already in requirements.txt")
        return
    
    # Add reportlab to requirements
    with open(requirements_file, 'a') as f:
        f.write('\nreportlab>=4.0.0\n')
    
    print("✅ Added ReportLab to requirements.txt")

def main():
    """Main setup function"""
    print("ReportLab Setup and Verification")
    print("=" * 40)
    
    # Check if ReportLab is already installed
    if check_reportlab():
        print("ReportLab is already properly installed!")
    else:
        print("ReportLab needs to be installed...")
        if install_reportlab():
            # Verify installation
            if not check_reportlab():
                print("❌ Installation verification failed")
                return False
        else:
            return False
    
    # Test basic PDF functionality
    print("\nTesting PDF generation...")
    if not test_basic_pdf():
        return False
    
    # Update requirements.txt
    print("\nUpdating requirements.txt...")
    update_requirements()
    
    print("\n" + "=" * 40)
    print("✅ ReportLab setup completed successfully!")
    print("You can now use ReportLab for PDF generation in your Django app.")
    
    return True

if __name__ == "__main__":
    success = main()
    if not success:
        print("\n❌ Setup failed. Please check the errors above.")
        sys.exit(1)
    else:
        print("\n🎉 Setup successful!")
        sys.exit(0)