# Generated by Django 4.2.7 on 2025-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='show_promotion_on_terminal',
            field=models.BooleanField(default=True, help_text='Show promotion status on terminal reports'),
        ),
        migrations.AddField(
            model_name='school',
            name='term_closing_date',
            field=models.DateField(blank=True, help_text='Term closing date to appear on terminal reports', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='term_reopening_date',
            field=models.DateField(blank=True, help_text='Term reopening date to appear on terminal reports', null=True),
        ),
    ]
