# Generated by Django 4.2.7 on 2026-02-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_show_promotion_on_terminal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='report_footer_text',
        ),
        migrations.RemoveField(
            model_name='school',
            name='report_header_text',
        ),
    ]
