# Generated by Django 4.2.7 on 2026-03-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_remove_school_report_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_term',
            field=models.ForeignKey(blank=True, help_text='Currently active term for the school', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_using_as_current', to='schools.term'),
        ),
    ]
