# Generated by Django 4.2.7 on 2025-12-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When assignment becomes available', null=True),
        ),
    ]
