# Generated by Django 4.2.7 on 2026-01-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='Whether answer matching is case sensitive'),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_answer',
            field=models.TextField(blank=True, help_text='Expected answer for short answer questions'),
        ),
    ]
