# Generated by Django 4.2.7 on 2026-01-02 22:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_dailyattendance'),
        ('assignments', '0004_timed_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(help_text='Which attempt this is (1, 2, etc.)')),
                ('submission_text', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='attempt_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png', 'txt'])])),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment_attempts',
                'ordering': ['-attempt_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='taskanswer',
            name='unique_attempt_question',
        ),
        migrations.RemoveConstraint(
            model_name='taskattempt',
            name='unique_task_student',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='attempts_count',
            field=models.IntegerField(default=0, help_text='Number of times student has attempted this assignment'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='max_attempts',
            field=models.IntegerField(default=2, help_text='Maximum number of attempts allowed'),
        ),
        migrations.AlterUniqueTogether(
            name='taskanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='taskattempt',
            unique_together={('task', 'student')},
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='student_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.studentassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentattempt',
            unique_together={('student_assignment', 'attempt_number')},
        ),
    ]
