# Generated by Django 4.2.7 on 2026-02-21 23:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_school_show_promotion_on_terminal_and_more'),
        ('students', '0006_alter_behaviour_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('DEFAULTED', 'Defaulted')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='schools.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee', to='students.student')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'school')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('collection_period', models.CharField(choices=[('TERM', 'Per Term'), ('YEAR', 'Per Year'), ('MONTH', 'Per Month')], default='TERM', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='fees.feetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school')),
            ],
            options={
                'ordering': ['fee_type', 'level'],
                'unique_together': {('school', 'fee_type', 'level')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(help_text='Admin or Class Teacher who collected the fee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collections', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['student', 'payment_date'], name='fees_feepay_student_198476_idx'), models.Index(fields=['school', 'payment_date'], name='fees_feepay_school__d7ac4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_students_paid', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('class_assigned', models.ForeignKey(blank=True, help_text='Class if collected by class teacher, None if collected by admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.class')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_sessions', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='schools.school')),
            ],
            options={
                'ordering': ['-collection_date'],
                'indexes': [models.Index(fields=['collected_by', 'collection_date'], name='fees_feecol_collect_3b7d7d_idx'), models.Index(fields=['school', 'collection_date'], name='fees_feecol_school__24194b_idx')],
            },
        ),
    ]
